---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-camel
spec:
  template:
    spec:
      containers:
        - name: apache-camel
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-dev-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-dev-db-secret
                  key: password
            - name: DB_DATABASE
              value: devdb
              valueFrom: null
            - name: DB_SCHEMA
              value: public
              valueFrom: null
            - name: HOST_NAME
              value: localhost:8080/
              valueFrom: null
