---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://scm.citc.ru/citc/infra/common-k8s-development-configs.git//postgresql?ref=48169ce83d1e71ae931cd0fe3b688ce316806b8b
  - apache-camel-db.yaml
