#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: apache-camel
#  labels:
#    app.kubernetes.io/name: apache-camel
#imagePullSecrets:
#  - name: dockerreg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-camel
  labels:
    app.kubernetes.io/name: apache-camel
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apache-camel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apache-camel
    spec:
      containers:
        - name: apache-camel
          image: dreg.citc.ru/ru.citc.education/spring-camel-test
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apache-camel-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apache-camel-db-secret
                  key: password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: apache-camel-db-secret
                  key: database
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: apache-camel-db-secret
                  key: database
            - name: HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: apache-camel-db-secret
                  key: hostname
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          # reads: application.properties
          volumeMounts:
            - name: apache-camel-config
              mountPath: /config
      volumes:
        - name: apache-camel-config
          configMap:
            name: apache-camel-config-map
            optional: true
