apiVersion: v1
kind: Service
metadata:
  name: apache-camel
  labels:
    app.kubernetes.io/name: apache-camel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apache-camel
  ports:
    - name: http
      port: 8080
      targetPort: 8080
